### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Ash-ketchm** [teeotsa/windows-8-debloat#5]
I wanna try this but I am scared it will wipe my data 
what should I do
What are all the things happen if I run this 
Please help

**Comment by teeotsa** [comment]
Hey!

Sorry for late response, lost access to my account

I advise you to make backup(s) before running this script.

> What are all the things happen if I run this

Well, script will basically disable bunch of services, for example WiFi related ones, Remote Desktop, Windows Defender/Firewall.

If you have any more questions, let me know :)
